const ACTION_TYPES = {
  LEAGUES: {
    GET_ALL: "LEAGUES__GET_ALL",
    SET_SELECTED:"LEAGUES__SET_SELECTED",
    GET_DETAILS: "LEAGUES__GET_DETAILS",
    SET_SELECTED_TEAMS: "LEAGUES__SET_SELECTED_TEAMS",

  },
  TEAMS: {
    GET_ALL: "TEAMS__GET_ALL",
    GET_DETAILS: "TEAMS__GET_DETAILS"
  }
};

export default ACTION_TYPES;
